name: Deploy to Cloudflare Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: cloudflare-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Install asdf
        uses: asdf-vm/actions/setup@v3
      - name: Cache asdf
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.asdf
          key: asdf-${{ hashFiles('**/.tool-versions') }}
      - name: install asdf plugins and tools
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          asdf plugin add ruby
          asdf plugin add pandoc https://github.com/aksdb/asdf-pandoc.git
          asdf install
      - name: install ruby gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: build website
        run: make
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 172af9127a9642800024b76b4bec0524
          projectName: simplexity-quest
          directory: generated/public
